version: '3.7'

services:
  postgresql:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:${MONGODB_VERSION}
    ports:
      - ${MONGODB_HOST_PORT}:${MONGODB_PORT}
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_PORT}
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    volumes:
      - redis_data:/data

volumes:
  postgresql_data:
    driver: local
  mongodb_data:
    driver: local
  redis_data:
    driver: local
