version: '3.7'

services:
  postgresql:
    image: ${POSTGRES_DOCKER_IMAGE}
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_PORT}
    restart: always
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASS}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}

  mongodb:
    image: ${MONGODB_DOCKER_IMAGE}
    ports:
      - ${MONGODB_HOST_PORT}:${MONGODB_PORT}
    restart: always
    environment:
      - MONGODB_USERNAME=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASS}
      - MONGODB_DATABASE=${MONGODB_DB}

  redis:
    image: ${REDIS_DOCKER_IMAGE}
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_PORT}
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
