name: CI-api

on:
  push:
    branches: ['main']
    paths:
      - './api/*'

  workflow_dispatch:

defaults:
  run:
    working-directory: ./api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16.x

      - name: Cache yarn
        uses: c-hive/gha-yarn-cache@v2
        with:
          directory: api

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Copy via ssh to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: 'api/dist,api/yarn.lock,api/package.json,api/tmp'
          target: '~/apps'

      - name: Install dependencies on Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/apps/api
            yarn
            cp ../gobarber-api.env ~/apps/api/.env
            cp ../docker-compose-production.yaml ~/apps/api/docker-compose.yaml

      - name: Run migrations and start api
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/apps/api
            yarn migration:run
            cp dist/ormconfig.js .
            yarn pm2:restart
